---
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - app/controllers/*
    - Rakefile

Metrics/MethodLength:
  Enabled: true
  Max: 20

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*