---
development:
  DATABASE_URL: sqlite://app/database/store/development.db
  DB_KEY: ZyB7hoZTxDD4zBeH/jwVXnV32ApoI15DUwM1f0MUNgU=
  SECURE_SCHEME: HTTP

test:
  DATABASE_URL: sqlite://app/database/store/test.db
  DB_KEY: qhj3ECW69ws+vZ5OmnYWhQ38pIg0vzX/NrpPf30uaYU=
  SECURE_SCHEME: HTTP

production:
  SECURE_SCHEME: HTTPS